---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
# - name: build-trivy
#   pull: if-not-exists
#   image: plugins/docker
#   settings:
#     dockerfile: Dockerfile
#     force_tag: true
#     registry: quay.io
#     repo: quay.io/ukhomeofficedigital/trivyscanner
#     tags:
#     - ${DRONE_COMMIT_SHA}
#     - b${DRONE_BUILD_NUMBER}-dev
#   environment:
#     DOCKER_PASSWORD:
#       from_secret: docker_password
#     DOCKER_USERNAME:
#       from_secret: docker_username
#   when:
#     event:
#     - push

- name: build-master
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - docker login -u="ukhomeofficedigital+trivyscanner" -p=$${docker_password} quay.io
    - docker tag alpine:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/trivyscanner:latest
    - docker tag alpine:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/trivyscanner:$${DRONE_TAG}
    - docker push quay.io/ukhomeofficedigital/alpine:latest
    - docker push quay.io/ukhomeofficedigital/alpine:$${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
    when:
      event:
      - push
  # when:
  #   branch:
  #     include: [ master ]
  #   event: push

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind




...
