pipeline:

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-management-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - TIMEOUT=10m0s
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - kd -f kube/service.yaml -f kube/deployment.yaml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
    when:
      event: [push, tag, deployment]
