---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivyscanner-deployment
  labels:
    app: trivy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: trivy
    spec:
      containers:
        - name: trivyscanner-container
          image: quay.io/ukhomeofficedigital/anchore-submission:latest
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - containerPort: 5001
